# PARA COMENTAR UNA SOLA LINEA DE CODIGO 
# SELECCIONANDO Y LUEGO PRESIONANDO CTRL+K+C EN VISUAL STUDIO CODE

""" DE ESTA FORMA SE COMENTAN VARIAS LINEAS DE CODIGO 
CON TRIPLE COMILLAS DOBLES 
EN VISUAL STUDIO CODE PRESIONANDO ALT + SHIF + A """




